config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"

  resources :items do
    resources :orders, only:[:index, :create] 
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
  has_many :orders

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    follower =  passive_relationships.find_by(following_id: user.id)
    return follower.present?
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'が無効です 全角文字を入力してください' }
    validates :last_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'が無効です 全角文字を入力してください' }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー]+\z/, message: 'が無効です 全角カタカナを入力してください' }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー]+\z/, message: 'が無効です 全角カタカナを入力してください' }
    validates :birthday
  end
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字の混在で入力してください' }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @items = @user.items.order(created_at: :desc)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="item-show">
<div class="user-page">
  <div class="user-contents">
    <p class="user-name"><%= @user.nickname %></p>
    <% if current_user != @user %>
      <% if @user.followed_by?(current_user) %>
        <%=link_to "フォロー中", user_relationships_path(@user.id),class: "btn" , method: :delete %>
      <% else %>
        <%=link_to "フォローする", user_relationships_path(@user.id),class: "btn" ,method: :post %>
      <% end %>
    <% end %>
    <div class="followfollower">
      <div class=follow ><div id="follow">フォロー</div>
        <ul class="follow-lists hidden" id="follow-pull-down">
          <% @user.followings.each do |user| %>
            <li class=“f-user”><%= link_to user.nickname, user_path(user.id) %></li>
          <% end %>
         </ul>
      </div>
      <div class=follower><div id="follower">フォロワー</div>
        <ul class="follower-lists hidden" id="follower-pull-down">
          <% @user.followers.each do |user| %>        
            <li class=“f-user”><%= link_to user.nickname, user_path(user.id) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

  <ul class='user-item-lists'>
    <% @items.each do |item| %>
        <%= link_to item_path(item.id) do%>
        <li class='list'>
        <div class='item-img-content'>
          <%= image_tag item.image, class: 'item-img'  %>
          <% if item.order.presence %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br><%= item.postage.name %></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

<%= render "shared/footer" %>